[forest]
trees = ["trees" ]                   # The directories in which your trees are stored
assets = ["assets"]                  # The directories in which your assets are stored
theme = "theme"                      # The directory in which your theme is stored
root = "xxx-0001"                     # The address of the root tree
base_url = "https://www.example.com" # The base URL of your site
